package FileManager;

import java.io.IOException;

public final class VhdlWriter extends FileWriter {
    protected VhdlWriter() { super(); }

    @Override
    public void writeHeader() throws IOException {
        write("----------------------------------------------------------------------------------\n");
        write("-- \n");
        write("-- File generated by DLX Assembler\n");
        write("-- ROM Entity for DLX Microprocessor\n");
        write("-- \n");
        write("----------------------------------------------------------------------------------\n");
        write("\n");
        write("\n");
        write("library IEEE;\n");
        write("use IEEE.STD_LOGIC_1164.ALL;\n");
        write("use IEEE.STD_LOGIC_UNSIGNED.ALL;\n");
        write("\n");
        write("entity ROM is\n");
        write("    Port ( Address : in STD_LOGIC_VECTOR (7 downto 0);\n");
        write("           Instruction : out STD_LOGIC_VECTOR (31 downto 0));\n");
        write("end ROM;\n");
        write("\n");
        write("architecture Behavioral of ROM is\n");
        write("type MEMORY_T is array (0 to 255) of STD_LOGIC_VECTOR(31 downto 0);\n");
        write("\n");
        write("signal MEM : MEMORY_T := (");
        write("\n");
    }

    @Override
    public void writeFooter() throws IOException {
        write("\tothers => x\"00000000\"\n");
        write(");\n");
        write("\n");
        write("begin\n");
        write("    Instruction <= MEM(conv_integer(Address));\n");
        write("end Behavioral;\n");
    }
}
